# Imagen base de Python
FROM python:3.9-slim

# Directorio de trabajo en el contenedor
WORKDIR /app

# Se copia el archivo requirements.txt al contenedor
COPY requirements.txt .

# Se instalan las dependencias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Se copian todos los archivos del proyecto al contenedor
COPY . .

# Se expone el puerto 8000 para acceder a la API
EXPOSE 8000

# Comando para ejecutar la API cuando el contenedor se inicie
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
